set -g mouse on
set -g status-position top
set -g prefix C-a
unbind C-b
bind C-a send-prefix
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
set -g base-index 1
setw -g pane-base-index 1

set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#[fg=#{@thm_green}] #{battery_icon} #{battery_percentage} "

run ~/.config/tmux/plugins/tmux-battery/battery.tmux
